const express = require("express") // express variable...
const app = express() // constructor...
// JSON javascript object notation.....
// objects(key value)....
app.use(express.json())
// get api ,put api,put api,delete....
// get fun first get path......2nd a function..
// req and res have the header and the body.....
// header having meta data.(title)...
// actual content in body........
 function addNums(req,res){
    const a = req.body.a; //req se a aur b ko nikal liya...
    const b = req.body.b;
    const name = req.body.name;
    console.log(name);

    const sum = a + b;
    res.send({"sum":sum});
 }
app.get('/addTwoNums', addNums)
// to call api....
// IP address +port NO...=>sockets..

const port = 3001
const ip = "localhost"
app.listen(port,ip,function(){
    console.log("I an Listening");
})




